name: release

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  release-server:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install rust
        uses: dtolnay/rust-toolchain@stable

      - name: install cargo-deb
        run: cargo install cargo-deb

      - name: build
        run: cargo deb

      - name: give binary a representative name
        run: cp target/release/server server-x86_64-unknown-linux-gnu

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          tag: latest
          artifacts: server-x86_64-unknown-linux-gnu,target/debian/obj-load_0.1.0_amd64.deb
          token: ${{ secrets.GITHUB_TOKEN }}

  release-client:
    runs-on: ${{ matrix.build.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { os: macos-latest,  target: x86_64-apple-darwin      }
          - { os: macos-latest,  target: aarch64-apple-darwin     }
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.build.target }}

      - name: compile obj-download
        run: cargo build --bin obj-download --features=bin-obj-download --release --target ${{ matrix.build.target }}

      - name: compile obj-upload
        run: cargo build --bin obj-upload --features=bin-obj-upload --release --target ${{ matrix.build.target }}

      - name: give executables representable name
        run: |
          cp target/${{ matrix.build.target }}/release/obj-download ./obj-download-${{ matrix.build.target }}
          cp target/${{ matrix.build.target }}/release/obj-upload ./obj-upload-${{ matrix.build.target }}

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          tag: latest
          artifacts: obj-download-${{ matrix.build.target }},obj-upload-${{ matrix.build.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
